### PR TITLE
replace medien map with map according the ZB MEDs list

### PR DESCRIPTION
**Pull request by aquast**
Branch changes map for "Art der Datei" fka "Medium" in order to match the ZB MEDs desires. As I used vocabularies and resources not instriduced before I'm not sure if this will be realy helpful. Please review patch

### CODE REVIEW

**Comment by aquast** [comment]
@jschnasse how can I assign Christoph to the PR?

**Comment by ChristophEwertowski** [comment]
I think at least I have to be a member of this group to be assigned.

**Comment by ChristophEwertowski** [comment]
For the supplement we use: http://id.loc.gov/ontologies/bibframe/supplement. For online fulltexts we have our own http://purl.org/lobid/lv#fulltextOnline. But as an alternative for http://pbcore.org/vocabularies/instantiationMediaType#text I would take http://purl.org/dc/dcmitype/Text because it's more widely used. But of course if you haven't already dublin core in use I would stick to pbcore for complexity reasons. 
An alternative for the license could be https://schema.org/license but dcterms is probably better.
(Note to myself: We really have to write something about how we choose vocabularies.)

**Comment by aquast** [comment]
Thank you Christoph for reviewing. I modified the uris in question according your suggestions. The licence I left unmodified as the dcterms seems to me best matching

**Pull request merged**
